export { default as Home } from "./Home/Home.jsx";
export { default as Search } from "./SearchResults/SearchResults.jsx";
export { default as Navbar } from "./Navbar/Navbar.jsx";
export { default as Footer } from "./Footer/Footer.jsx"
export { default as TermsAndPolicy } from "./Footer/TermsAndPolicy.jsx"
export { default as Pricing } from "./Footer/Pricing.jsx"
export { default as Login } from "./Login/Login.jsx";
export { default as Register } from "./Register/Register.jsx";
export { default as SpaceForm } from "./Space/spaceForm.jsx";
export { default as ScreensListing } from "./Screens/screenList.jsx";
export { default as BookingForm } from "./booking/bookingForm.jsx";
export { default as Profile } from "./Profile/Profile.jsx";
export { default as About } from "./About/About.jsx";
export { default as Contact } from "./Contact/Contact.jsx";
export { default as PageNotFound } from "./PageNotFound/PageNotFound.jsx";
